--- 
- hosts: test
  remote_user: root
  tasks:
  - name: lineinfile file
    lineinfile:
      path: /root/ansible/ip
      line: " test "
      regexp: "^ansible"
      #state: absent
      backrefs: yes
     
   
